export {default as Home } from './Home'
export {default as AddPrograms} from './dashboard/AddPrograms'
export {default as Review} from './Review'
export {default as Catalog} from './catalog/Catalog'
export {default as Navbar} from './navbar/Navbar'